<script type="text/javascript">
    require([
        'jquery',
        'owlcarousel'
    ], function($){
        $(document).ready(function() {
            $('.owl-carousel').owlCarousel({
                loop: true,
                nav: true,
                items: 1,
                dots: false,
                autoplay: true,
                autoplayTimeout: 3000,
                responsiveClass:true,
                responsive: {
                    0: {
                        items: 1
                    },
                    480: {
                        items: 1
                    },
                    768: {
                        items: 1
                    }
                }
            })
        });
    });
</script>
